import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NorthwindApiService } from '../../core/api/northwind-api.service';
import { DashboardKpisResponse } from '../../core/api/northwind-api.models';

@Component({selector:'app-dashboard',standalone:true,imports:[FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<h1>Executive Dashboard</h1><form (ngSubmit)="load()"><label>Region <input name="region" [(ngModel)]="region"></label><label>From <input name="from" type="date" [(ngModel)]="from"></label><label>To <input name="to" type="date" [(ngModel)]="to"></label><button>Apply</button></form>
@if (loading) { <p>Loading dashboard…</p> } @else if (error) { <p role="alert">Unable to load dashboard.</p> } @else if (data) { <p>Period: {{data.period.from}} to {{data.period.to}}</p><section>@for (metric of metricEntries(); track metric[0]) { <article><strong>{{metric[0]}}</strong><span>{{metric[1] ?? 'Not available'}}</span></article> }</section><h2>Complaint trend <small>GLOBAL</small></h2>@if(!data.trends.length){<p>No source data available.</p>}@else{<table><tr><th>Month</th><th>Opened</th><th>Closed</th><th>FCR (GLOBAL)</th></tr>@for (point of data.trends; track point.month){<tr><td>{{point.month}}</td><td>{{point.complaintsOpened}}</td><td>{{point.complaintsClosed}}</td><td>{{point.firstContactResolutionPercent ?? 'Not available'}}</td></tr>}</table>}<h2>Estimated read trend</h2><table>@for(point of data.estimatedReadTrend;track point.month){<tr><td>{{point.month}}</td><td>{{point.estimatedReadRatePercent ?? 'Not available'}}</td><td>{{point.scope}}</td></tr>}</table> }`,styles:`section{display:grid;grid-template-columns:repeat(auto-fit,minmax(10rem,1fr));gap:1rem}article{border:1px solid #ccc;padding:1rem}form{display:flex;gap:.5rem;flex-wrap:wrap}table{width:100%;margin:1rem 0}`})
export class DashboardComponent { private api=inject(NorthwindApiService); data:DashboardKpisResponse|null=null;loading=false;error=false;region='';from='';to='';constructor(){this.load()} load(){this.loading=true;this.error=false;const p:Record<string,string>={};if(this.region)p['region']=this.region;if(this.from&&this.to){p['from']=this.from;p['to']=this.to}this.api.dashboard(p).subscribe({next:d=>{this.data=d;this.loading=false},error:()=>{this.error=true;this.loading=false}})} metricEntries(){return this.data?Object.entries(this.data.metrics):[]} }
