package com.northwind.resolve.analytics.application

import com.northwind.resolve.analytics.api.*
import com.northwind.resolve.analytics.persistence.AnalyticsReadRepository
import com.northwind.resolve.analytics.persistence.MeterMetricRow
import org.springframework.stereotype.Service
import org.springframework.context.annotation.Profile
import java.math.BigDecimal
import java.math.RoundingMode
import java.time.Instant
import java.time.LocalDate

@Service @Profile("database") class AnalyticsService(private val repository: AnalyticsReadRepository) {
    fun dashboard(region: String?, from: LocalDate?, to: LocalDate?): DashboardKpisResponse { val period = period(from,to); val kpis=repository.monthlyKpis(period.from,period.to); val counts=repository.complaintCounts(period.from,period.to,region); val scope=if(region.isNullOrBlank())"GLOBAL" else "REGION"; val weight=kpis.sumOf{it.opened}; val fcr=if(weight==0)null else kpis.fold(BigDecimal.ZERO){ total,row->total+(row.fcr?:BigDecimal.ZERO)*BigDecimal(row.opened)}.divide(BigDecimal(weight),6,RoundingMode.HALF_UP).multiply(BigDecimal(100)).setScale(2,RoundingMode.HALF_UP); val metrics=DashboardMetrics(repository.backlog(region),percent(counts.first-counts.second,counts.first),fcr,percent(counts.third,counts.first),percent(repository.reopenedCount(period.from,period.to,region),counts.first),repository.billingExceptions(period.from,period.to,region),weightedRate(repository.meterRows(period.from,period.to,region))); val global=trace("monthly_kpis",period,"OBSERVED","GLOBAL"); val regional=trace("legacy_complaints",period,"CALCULATED",scope); return DashboardKpisResponse(Instant.now(),period,metrics,kpis.map{DashboardTrendPoint(it.month,it.opened,it.closed,it.fcr?.multiply(BigDecimal(100))?.setScale(2,RoundingMode.HALF_UP))},repository.meterRows(period.from,period.to,region).groupBy{it.month}.map{(month,rows)->EstimatedReadTrendPoint(month,weightedRate(rows),scope)},mapOf("backlog" to trace("cases",period,"OBSERVED",scope),"slaCompliancePercent" to regional,"firstContactResolutionPercent" to global,"transferRatePercent" to regional,"reopenRatePercent" to regional,"billingExceptionCount" to trace("billing_exceptions",period,"OBSERVED",scope),"estimatedReadRatePercent" to trace("meter_region_monthly_metrics",period,"CALCULATED",scope),"complaintTrend" to global)) }
    fun valueCase(c: BigDecimal?,t: BigDecimal?,o: BigDecimal?,i: BigDecimal?): ValueCaseResponse { val period=period(null,null); val annual=repository.monthlyKpis(period.from,period.to).sumOf{it.opened}; val transferred=repository.complaintCounts(period.from,period.to,null).third; val average=repository.unitCost("Complaint handled end to end (average)"); val transferredCost=repository.unitCost("Complaint handled end to end (transferred between systems)"); val observed=ValueCaseObservedBaseline(annual,transferred,average,transferredCost,repository.correctionCount(period.from,period.to)); val assumptions=ValueCaseAssumptions(c,t,o,i); val complete=listOf(c,t,o,i,average,transferredCost).all{it!=null}; val complaint=if(complete)money(BigDecimal(annual).multiply(c!!).divide(BigDecimal(100)).multiply(average!!))else null; val transfer=if(complete){val complaintFraction=c!!.divide(BigDecimal(100));val transferFraction=t!!.divide(BigDecimal(100));val incremental=transferredCost!!.subtract(average!!);money(BigDecimal(transferred).multiply(BigDecimal.ONE.subtract(complaintFraction)).multiply(transferFraction).multiply(incremental))}else null; val gross=if(complete)money(complaint!!+transfer!!)else null; val net=gross?.let{money(it-o!!)}; val payback=if(net!=null&&net>BigDecimal.ZERO)money(i!!/net*BigDecimal(12))else null; return ValueCaseResponse(period,assumptions,observed,complaint,transfer,gross,if(complete)o else null,net,payback,mapOf("observedBaseline" to trace("monthly_kpis,legacy_complaints,unit_costs",period,"OBSERVED","GLOBAL"),"scenario" to trace("request parameters",period,"ASSUMPTION","GLOBAL"),"projectedBenefit" to trace("value-case formulas",period,"CALCULATED","GLOBAL","Projected modeled benefit; not realized savings."))) }
    private fun period(from:LocalDate?,to:LocalDate?):AnalyticsPeriod{require((from==null)==(to==null)){"from and to must be supplied together"};if(from!=null){require(!to!!.isBefore(from)){"to must be on or after from"};return AnalyticsPeriod(from,to)};val months=repository.latestMonths();require(months.isNotEmpty()){"No source KPI months are available"};return AnalyticsPeriod(months.first(),months.last())}
    private fun percent(n:Int,d:Int)=if(d==0)null else BigDecimal(n*100).divide(BigDecimal(d),2,RoundingMode.HALF_UP)
    private fun weightedRate(rows:List<MeterMetricRow>):BigDecimal?{val total=rows.sumOf{it.accounts};return if(total==0)null else rows.fold(BigDecimal.ZERO){v,r->v+(r.rate?:BigDecimal.ZERO)*BigDecimal(r.accounts)}.divide(BigDecimal(total),6,RoundingMode.HALF_UP).multiply(BigDecimal(100)).setScale(2,RoundingMode.HALF_UP)}
    private fun money(v:BigDecimal)=v.setScale(2,RoundingMode.HALF_UP)
    private fun trace(source:String,period:AnalyticsPeriod,classification:String,scope:String,formula:String?=null)=MetricTrace(source,period,classification,scope,formula)
}
