import { provideZonelessChangeDetection } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of, throwError } from 'rxjs';
import { CaseWorkspaceComponent } from './case-workspace.component';
import { NorthwindApiService } from '../../core/api/northwind-api.service';

describe('CaseWorkspaceComponent', () => {
  let fixture: ComponentFixture<CaseWorkspaceComponent>;
  let transferCalls = 0; let visitCalls = 0; let failTransfer = false; let failVisit = false;
  const api = { caseContext: () => of({ case: { caseId: 'NW-100001', accountId: 'ACC-943644', category: 'BILLING', priority: 'MEDIUM', region: 'Ashford', status: 'CLOSED', slaDays: 20, openedAt: '2024-10-01T00:00:00Z', closedAt: null, assignedTeam: 'UNASSIGNED_IMPORT' }, latestBillingException: null, latestMeterReading: null, fieldVisits: [] }), timeline: () => of({ caseId: 'NW-100001', events: [{ eventId: '1', caseId: 'NW-100001', eventType: 'COMPLAINT_CREATED', sourceSystem: 'CASETRACK', timestamp: '2024-10-01T00:00:00Z', actor: 'CSV_IMPORT', description: 'Imported complaint record' }] }), billingHistory: () => of({ accountId: 'ACC-943644', bills: [], corrections: [] }), meterReadings: () => of({ accountId: 'ACC-943644', readings: [] }), transferCase: () => { transferCalls++; return failTransfer ? throwError(() => new Error('failed')) : of({}); }, requestFieldVisit: () => { visitCalls++; return failVisit ? throwError(() => new Error('failed')) : of({}); } };
  beforeEach(async () => { await TestBed.configureTestingModule({ imports: [CaseWorkspaceComponent], providers: [provideZonelessChangeDetection(), provideRouter([]), { provide: ActivatedRoute, useValue: { snapshot: { paramMap: new Map([['caseId', 'NW-100001']]) } } }, { provide: NorthwindApiService, useValue: api }] }).compileComponents(); fixture = TestBed.createComponent(CaseWorkspaceComponent); });
  it('renders case data and truthful empty source-data sections', () => { fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('NW-100001'); expect(fixture.nativeElement.textContent).toContain('No account-level meter readings'); expect(fixture.nativeElement.textContent).toContain('No FieldForce visits'); });
  it('submits transfer and field-visit actions then refreshes the workspace', () => { fixture.detectChanges(); fixture.componentInstance.assignedTeam = 'RESOLUTION'; fixture.componentInstance.transfer(); fixture.componentInstance.requestedFor = '2026-09-28T10:00'; fixture.componentInstance.visitReason = 'Inspect meter'; fixture.componentInstance.requestVisit(); expect(transferCalls).toBe(1); expect(visitCalls).toBe(1); expect(fixture.componentInstance.transferMessage()).toBe('Case transferred.'); expect(fixture.componentInstance.visitMessage()).toBe('Field visit requested.'); });
  it('shows action errors without replacing the case workspace', () => { failTransfer = true; failVisit = true; fixture.detectChanges(); fixture.componentInstance.assignedTeam = 'RESOLUTION'; fixture.componentInstance.transfer(); fixture.componentInstance.requestedFor = '2026-09-28T10:00'; fixture.componentInstance.visitReason = 'Inspect meter'; fixture.componentInstance.requestVisit(); expect(fixture.componentInstance.transferMessage()).toContain('could not be transferred'); expect(fixture.componentInstance.visitMessage()).toContain('could not be requested'); });
});
