package com.northwind.resolve.cases.domain

enum class CaseStatus { OPEN, IN_PROGRESS, PENDING_FIELD_VISIT, RESOLVED, CLOSED }
enum class CaseCategory { BILLING, METERING, SERVICE, COMPLAINT, OTHER }
enum class CasePriority { LOW, MEDIUM, HIGH, CRITICAL }
enum class CaseEventType { COMPLAINT_CREATED, TRANSFERRED, BILL_CHECKED, METER_REVIEWED, FIELD_VISIT_REQUESTED, FIELD_VISIT_COMPLETED, BILL_CORRECTED, CASE_CLOSED }
enum class SourceSystem { RESOLVE, CASETRACK, METERHUB, BILLING, FIELDFORCE, CALLCENTRE }
